---
title: "Predicting house price data using Yelp/Zillow data"
output: 
  github_document:
    pandoc_args: --webtex
--- 

#### Data Used

- [Zillow](https://www.zillow.com/research/data/)
- [Yelp](https://www.yelp.com/dataset)


#### The goal of this project is to try to quantify what the role of textual data (in the form of restaraunt reviews) in predicting house price growth

To formalize this, we can think of the following model that states house prices are a function of Yelp star ratings plus review data with $\epsilon_{zy}$ capturing everything else the Yelp data doesn't capture. $f()$ represnts the model that uses both stars and rewview, and $g()$ represents the model that only uses stars. 

$$
\begin{aligned}
    P_{zy}&=f(Star_{zy},Review_{zy},Other_{zy}) + \epsilon_{zy} \\
    P_{zy}&=g(Star_{zy},Other_{zy}) + \epsilon_{zy}
\end{aligned}
$$
In terms of the variables: 

- $P_{zy}$- House prices from `Zillow`
- $Star_{zy}$- Star ratings from `Yelp`
- $Review_{zy}$- Text reviews from `Yelp`
- $Other_{zy}$- Other variables like `population`,`income`,`unemployment` that may explain house price growth

and $z$ is zipcode, $y$ is the year

We can use machine learning models to predict $\hat{f}() \ and \ \hat{g}()$ (which the hat signifies). Once we predict these functions, we can compare the predictions to see which one is more accurate. 

### Issue with levels vs difference
If our goal is to predict house price growth, the current specification is insufficient because it will just tell us which zipcodes are associated with high house prices. For example, in general, zipcodes with higher restaurant ratings may have higher hosue prices. BUt that doesn't tell us much about how **changes** in restaurant ratings lead to **changes** in house price growth. Therefore, we need to respecify the equation in terms of differences as below. Furthermore, we want to look at the change in **log** prices so that we can interpret these as percentage changes. 

$$
\begin{aligned}
    \Delta log(P_{zy})&=f(\Delta Star_{zy},\Delta Review_{zy},\Delta Other_{zy}) + \epsilon_{zy} \\
    \Delta log(P_{zy})&=g(\Delta Star_{zy},\Delta Other_{zy}) + \epsilon_{zy}
\end{aligned}
$$


## Ongoing issues

- The dataset we are provided is very unbalanced when it comes to geographical location
